name: ImportadoraBicentenario
favicon: null
layout_spectrum: 0.9276888279709965
typography_spectrum: 0.7922
title: Distributor  IBC
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9f0513'
    - '#ffffff'
    - '#e0bbbc'
    - '#b64a53'
    - '#cf9798'
  brandStrength: 0.679485023021698
  lightness: 0.9818446987774223
  saturation: 0.7989294184371829
  rhythmicContrast: 0.7919140129815787
purpose: []
